apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-default-consul-consul-server-0
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-default-consul-consul-server-1
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-default-consul-consul-server-2
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
