apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: opsschool-project
  labels:
    app: opsschool-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opsschool-project
  template:
    metadata:
      labels:
        app: opsschool-project
    spec:     
      containers:
      - name: opsschool-project
        image: carmitbe1/opsschool-project
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:  
  name: opsschool-project
spec:
  selector:    
    app: opsschool-project
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP
