apiVersion: v1
kind: Pod
metadata:
  name: hw3
  labels:
    app: hw3
spec:
  containers:
    - image: training/webapp
      name: webapp
      ports:
      - containerPort: 8080
        name: http
        protocol: TCP
EOF