- hosts: all
  become: yes
  vars:
    ansible_host_key_checking: false
 
  tasks:
   - name: containerd Installation
     apt:
       name: containerd
       state: latest
       update_cache: true

   - name: Docker Installation
     apt:
       name: docker.io
       state: latest
       update_cache: true
   
   - name: install APT Transport HTTPS
     apt:
       name: apt-transport-https
       state: present

   - name: add Kubernetes apt-key for APT repository
     apt_key:
       url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
       state: present

   - name: add Kubernetes APT repository
     apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'

   - name: install kubelet
     apt:
       name: kubelet
       state: present
       update_cache: true

   - name: install kubeadm
     apt:
       name: kubeadm
       state: present

   - name: start docker
     service:
       name: docker
       state: started
       enabled: yes
       masked: no

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl
       #=1.14.0-00
       state: present
       force: yes

